title: Motion of a Spring
description: A model of the motion of a spring
baseurl: "/spring" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github: https://github.com/dulldesk/spring/

defaults:
  - scope:
      path: ""
    values:
      layout: default
      mathjax: true

exclude: ["*-cache/", "Gemfile*", "**/README.md", "README.md"]

sass:
  style: compressed
